name: rosiewise
favicon: null
layout_spectrum: 0.4726350726559758
typography_spectrum: 0.4973081713542342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.27996625774540007
  lightness: 0.7198807443492115
  saturation: 0.4297688826918602
  rhythmicContrast: 0.2745220339857042
purpose: []
